---
Name: silverstripe-inline-image-quality
---
SilverStripe\Assets\Image:
  extensions:
    - Kinglozzer\SilverStripeInlineImageQuality\Extensions\ImageExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - Kinglozzer\SilverStripeInlineImageQuality\Extensions\ImageExtension
